name: eclipse for embedded arm

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
    branches:
      - master
  workflow_dispatch:

jobs:
  eclipse:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        with_jre: [true, false]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Java
        if: ${{ matrix.with_jre == false }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
      - name: Download Eclipse
        run: |
          curl -L "https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.40-202606010713/eclipse-platform-4.40-win32-win32-x86_64.zip&r=1" --output eclipse.zip
          7z x eclipse.zip
      - name: Download and install JRE
        if: ${{ matrix.with_jre == true }}
        run: |
          curl -L "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.9%2B10/OpenJDK21U-jre_x64_windows_hotspot_21.0.9_10.zip" --output jre.zip
          7z x jre.zip
          move .\*-jre .\eclipse\jre
      - name: Install plugins
        run: |
          .\eclipse\eclipsec -nosplash -application org.eclipse.equinox.p2.director -repository https://download.eclipse.org/releases/2026-06 -installIU org.eclipse.cdt.feature.group,org.eclipse.cdt.debug.gdbjtag.feature.group,org.eclipse.embedcdt.managedbuild.cross.arm.feature.group,org.eclipse.embedcdt.debug.gdbjtag.jlink.feature.group,org.eclipse.embedcdt.debug.gdbjtag.openocd.feature.group
      - name: Deploy - create file name with JRE
        if: ${{ matrix.with_jre == true }}
        run: |
          $NOW=& Get-Date -format yyyyMMddhhmmss
          echo "filename=eclipse-2026-06-with-jre-$NOW" >> $env:GITHUB_ENV
      - name: Deploy - create file name without JRE
        if: ${{ matrix.with_jre == false }}
        run: |
          $NOW=& Get-Date -format yyyyMMddhhmmss
          echo "filename=eclipse-2026-06-$NOW" >> $env:GITHUB_ENV
      - name: Deploy - 7z archive
        run: |
          7z a -mx=9 ${{ env.filename }}.7z .\eclipse\*
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: ${{ env.filename }}.7z
          path: ${{ env.filename }}.7z
  buildtools:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        sys: [ucrt64]
        include:
        - sys: ucrt64
          env: ucrt-x86_64
    steps:
      - name: Checkout branch
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install toolchain
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            make
            p7zip
            patch
            base-devel
            autoconf-wrapper
            automake-wrapper
            autotools
            libtool
            mingw-w64-${{matrix.env}}-toolchain
            mingw-w64-${{matrix.env}}-diffutils
      - name: Build make
        run: |
          wget https://mirror.twds.com.tw/gnu/make/make-4.4.1.tar.gz
          tar xvf make-4.4.1.tar.gz
          cd make-4.4.1
          patch -p1 < ../make-patchs/0001-make-linebuf-mingw.patch
          patch -p1 < ../make-patchs/0002-make-4.3_undef-HAVE_STRUCT_DIRENT_D_TYPE.patch
          patch -p1 < ../make-patchs/0005-fix-default-cxx.patch
          patch -p1 < ../make-patchs/0006-fix-build-with-gcc-15.patch
          patch -p1 < ../make-patchs/0007-make-4.4-timestamps.patch
          patch -p1 < ../make-patchs/0008-make-4.2.1-Makefile.am-gcc-only-link-libgnumake-1.dll.a.patch
          autoreconf -vfi
          ./configure -C --without-libintl-prefix --without-libiconv-prefix CPPFLAGS=-DMAKE_LOAD CFLAGS=-mthreads ac_cv_dos_paths=yes
          make -j2
          strip make.exe
      - name: Deploy - copy make to dist
        run: |
          mkdir -p dist
          cp -rf make-4.4.1/make.exe ./dist/
      - name: Checkout busybox
        uses: actions/checkout@v7
        with:
          repository: rmyorston/busybox-w32
          path: busybox-w32
      - name: Build busybox
        run: |
          cd busybox-w32
          make mingw64_defconfig
          make -j2
      - name: Deploy - copy busybox to dist
        run: |
          mkdir -p dist
          cp -rf busybox-w32/busybox.exe ./dist/
          cp -rf busybox-w32/busybox.exe ./dist/cp.exe
          cp -rf busybox-w32/busybox.exe ./dist/echo.exe
          cp -rf busybox-w32/busybox.exe ./dist/mkdir.exe
          cp -rf busybox-w32/busybox.exe ./dist/rm.exe
          cp -rf busybox-w32/busybox.exe ./dist/sh.exe
      - name: Deploy - create file name
        run: |
          echo "filename=build-tools-${{matrix.env}}-$(date +"%Y%m%d_%H%M%S")" >> $GITHUB_ENV
      - name: Deploy - 7z archive
        run: |
          7z a -mx=9 ${{ env.filename }}.7z ./dist/*
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: ${{ env.filename }}.7z
          path: ${{ env.filename }}.7z