name: Private Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ChiaYen-Kan/PixivRSS
          fetch-depth: 0
          path: ./PixivRSS
      - name: Test
        run: |
          find