name: Update certificate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update certificate
        run: bash ./scripts/update-certificate.sh
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: certificate-patch
          commit-message: 'chore: update certificate'
          title: Update certificate
          body: >-
            update ca-bundle.crt.